# Copyright By BiliHp (https://app.bilihp.com:444)

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-bilihp
PKG_VERSION:=1.2
PKG_RELEASE:=1

LUCI_TITLE:=Bilibili Helper for LuCI
LUCI_DESCRIPTION:=This package contains LuCI configuration pages for Bilibili Helper.
LUCI_DEPENDS:=+wget
LUCI_PKGARCH:=all



include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature